name: Build Go binaries

on:
  push:
    # We want to run the workflow on all branches.
    # But you can restrict the runs if necessary.
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: go-cross-build
        uses: thatisuday/go-cross-build@v1
        # Uncomment to following piece to restrict targets
        # with:
        #   args: linux/amd64 darwin/amd64
